title: "Rueben Gill - Portfolio"
description: "Python Developer | Computer Vision Specialist"
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/jtakilol/jtakilol.github.io