title: "Rueben Gill - Portfolio"
description: "Python Developer | Computer Vision Specialist"
theme: jekyll-theme-cayman
baseurl: ""
url: "https://jtakilol.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-theme-cayman
  - jekyll-feed  # Add any additional plugins you are using

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/